# -*- coding: utf-8 -*-
"""kucingmau

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eyNQNEwbtSnuADKSIYIKARPBzxDvNslt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from datetime import datetime
sns.set(style='dark')

order_item = pd.read_csv("https://raw.githubusercontent.com/Adevaaaa/Bangkit/main/order_items_dataset.csv")
order_payment = pd.read_csv("https://raw.githubusercontent.com/Adevaaaa/Bangkit/main/order_payments_dataset.csv")
product_translate = pd.read_csv("https://raw.githubusercontent.com/Adevaaaa/Bangkit/main/product_category_name_translation.csv")
product_dataset = pd.read_csv("https://raw.githubusercontent.com/Adevaaaa/Bangkit/main/products_dataset.csv")
order_dataset = pd.read_csv("https://raw.githubusercontent.com/Adevaaaa/Bangkit/main/orders_dataset.csv")

order_dataset.dropna(inplace=True)

def joinproduk(df,df2,df3):
  product_part1 = df.merge(df2, on="product_id", how="inner")
  product = product_part1.merge(df3, on="product_category_name",how="inner")

  return product

def hargaproduk(df):
  harga_product = df.groupby(by="product_category_name_english").agg({
    "price"  : "mean"
  }).sort_values(by="price",ascending=False)

  return harga_product

def banyakproduk(df):
  df["product_count"] = df["product_category_name_english"]
  banyak_product = df.groupby(by="product_category_name_english").agg({
    "product_count"  : "count"
  }).sort_values(by="product_count",ascending=False)
  return banyak_product

def carabayar(df):
  df["payment_count"] = df["payment_type"]
  cara_bayar = df.groupby(by="payment_type").agg({
    "payment_count"  : "count"
  }).sort_values(by="payment_count",ascending=False)
  return cara_bayar

def hargabayar(df):
  harga_bayar = df.groupby(by="payment_type").agg({
    "payment_value"  : "mean"
  }).sort_values(by="payment_value",ascending=False)
  return harga_bayar

def monthlyreport(df):
  df["order_purchase_timestamp"] = pd.to_datetime(order_dataset["order_purchase_timestamp"])
  df["bulan"] = df["order_purchase_timestamp"].dt.month_name()
  df["jumlah"] = 1
  df["bulan"] = sorted(df["bulan"])
  total_bulan = df.groupby("bulan")["jumlah"].sum()
  return total_bulan

order_dataset.info()

with st.sidebar:
    # Menambahkan logo perusahaan
    st.image("https://github.com/Adevaaaa/Bangkit/blob/509f7409d9bb99fe1b3f7e7545ad0552f15003a0/allmight.png")

product = joinproduk(order_item,product_dataset,product_translate)
harga_product = hargaproduk(product)
banyak_product = banyakproduk(product)
cara_bayar = carabayar(order_payment)
harga_bayar = hargabayar(order_payment)
total_bulan = monthlyreport(order_dataset)

st.header('Adeva Dashboard :fire:')

st.subheader("Payment")

col1, col2 = st.columns(2)

with col1 :
    fig, ax = plt.subplots(figsize=(35, 15))
    bars = plt.bar(cara_bayar.index,cara_bayar['payment_count'])
    for bar, value in zip(bars, cara_bayar['payment_count']):
      plt.text(bar.get_x() + bar.get_width() / 2, value + 100, str(value), ha='center', va='bottom')
    ax.set_title("Jenis Metode Pembayaran", loc="center", fontsize=15)
    st.pyplot(fig)

with col2 :
  fig, ax = plt.subplots(figsize=(35, 15))
  plt.bar(harga_bayar.index,harga_bayar['payment_value'])
  plt.title("Rata-rata nilai pembelian", loc="center", fontsize=7)
  st.pyplot(fig)

st.subheader("Product and Order")

col3, col4, col5 = st.columns(3)

with col3:
  fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(30, 15))

  sns.barplot(x="price", y="product_category_name_english", data=harga_product.head(5), ax=ax[0])
  ax[0].set_ylabel(None)
  ax[0].set_xlabel("price", fontsize=30)
  ax[0].set_title("Rata-rata Kategori Produk Tertinggi", loc="center", fontsize=50)
  ax[0].tick_params(axis='y', labelsize=35)
  ax[0].tick_params(axis='x', labelsize=30)

  sns.barplot(x="price", y="product_category_name_english", data=harga_product.sort_values(by="price", ascending=True).head(5), ax=ax[1])
  ax[1].set_ylabel(None)
  ax[1].set_xlabel("Harga", fontsize=30)
  ax[1].invert_xaxis()
  ax[1].yaxis.set_label_position("right")
  ax[1].yaxis.tick_right()
  ax[1].set_title("Rata-Rata Kategori Produk Terendah", loc="center", fontsize=50)
  ax[1].tick_params(axis='y', labelsize=35)
  ax[1].tick_params(axis='x', labelsize=30)

  st.pyplot(fig)

with col4:
  fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(30, 15))

  sns.barplot(x="product_count", y="product_category_name_english", data=banyak_product.head(5), ax=ax[0])
  ax[0].set_ylabel(None)
  ax[0].set_xlabel("Banyak Produk Terjual", fontsize=30)
  ax[0].set_title("Kategori Produk Tertinggi", loc="center", fontsize=50)
  ax[0].tick_params(axis='y', labelsize=35)
  ax[0].tick_params(axis='x', labelsize=30)

  sns.barplot(x="product_count", y="product_category_name_english", data=banyak_product.sort_values(by="product_count", ascending=True).head(5), ax=ax[1])
  ax[1].set_ylabel(None)
  ax[1].set_xlabel("Banyak Produk Terjual", fontsize=30)
  ax[1].invert_xaxis()
  ax[1].yaxis.set_label_position("right")
  ax[1].yaxis.tick_right()
  ax[1].set_title("Kategori Produk Terendah", loc="center", fontsize=50)
  ax[1].tick_params(axis='y', labelsize=35)
  ax[1].tick_params(axis='x', labelsize=30)

  st.pyplot(fig)


with col5:
  # Create a bar chart
  fig, ax = plt.subplots(figsize=(35, 15))
  plt.bar(total_bulan.index, total_bulan)
      # Add data labels (optional)
  ax.set_title("Order per bulan", loc="center", fontsize=50)
  ax.set_ylabel(None)
  ax.set_xlabel(None)
  ax.tick_params(axis='x', labelsize=35)
  ax.tick_params(axis='y', labelsize=30)
  st.pyplot(fig)

st.caption('Adevaaaaaa')
